# Manages a database table within ServiceNow. The internal `name` field is
# auto-generated by ServiceNow from the `label` (e.g. label "Example Table"
# becomes name "u_example_table" in the global scope).
resource "servicenow_db_table" "example" {
  label     = "Example Table"
  user_role = ""
}
